theme: jekyll-theme-hacker
title: Leonardo Collazo Klenina => Front-End Web Developer & Unity 3D Programmer
author: Leonardo Collazo Klenina <kidbourbongamer@gmail.com>
description: This page contains some personal information about the author, links to his social medias and GitHub repositories containing the projects he has been working on.
