theme: jekyll-theme-hacker
title: Leonardo Collazo - Unity Game Developer
author: Leonardo Collazo
description: This page contains some personal information about the author, links to his social medias and GitHub repositories containing the personal projects he has been working on.
